main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('pengalaman', views.pengalaman, name='pengalaman'),
    path('penggunaJasa', views.penggunaJasa, name='penggunaJasa'),
    path('pekerjaan', views.pekerjaan, name='pekerjaan'),
    path('layanan', views.layanan, name='layanan'),
    path('platform', views.platform, name='platform'),
]

office/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from office.db import Database


def home(request):
    return render(request, 'main/home.html')


def penggunaJasa(request):

    database = Database(schema='office')

    if request.method == 'GET':
        res = database.query('''
            SELECT * 
            FROM PENGGUNA_JASA
        ''')
        response = {
            'result': [
                {"id": pj[0],
                 "nama": pj[1]}
                for pj in res
            ]
        }
        return render(request, 'main/penggunaJasa.html', response)

    else:
        nama = request.POST.get('nama')
        res = database.query('''
            SELECT id
            FROM PENGGUNA_JASA
            ORDER BY id DESC
            LIMIT 1
        ''')
        if len(res) == 0:
            database.query(f'''
                INSERT INTO PENGGUNA_JASA VALUES 
                (1, '{nama}')
            ''')
        else:
            database.query(f'''
                INSERT INTO PENGGUNA_JASA VALUES 
                ({res[0][0] + 1}, '{nama}')
            ''')
        return HttpResponseRedirect('/penggunaJasa')


def pekerjaan(request):

    database = Database(schema='office')

    if request.method == 'GET':
        res = database.query('''
            SELECT * 
            FROM PEKERJAAN
        ''')
        response = {
            'result': [
                {"id": pj[0],
                 "nama": pj[1]}
                for pj in res
            ]
        }
        return render(request, 'main/pekerjaan.html', response)

    else:
        nama = request.POST.get('nama')
        res = database.query('''
            SELECT id
            FROM PEKERJAAN
            ORDER BY id DESC
            LIMIT 1
        ''')
        if len(res) == 0:
            database.query(f'''
                INSERT INTO PEKERJAAN VALUES 
                (1, '{nama}')
            ''')
        else:
            database.query(f'''
                INSERT INTO PEKERJAAN VALUES 
                ({res[0][0] + 1}, '{nama}')
            ''')
        return HttpResponseRedirect('/pekerjaan')


def layanan(request):

    database = Database(schema='office')

    if request.method == 'GET':
        res = database.query('''
            SELECT * 
            FROM LAYANAN
        ''')
        response = {
            'result': [
                {"id": pj[0],
                 "nama": pj[1]}
                for pj in res
            ]
        }
        return render(request, 'main/layanan.html', response)

    else:
        nama = request.POST.get('nama')
        res = database.query('''
            SELECT id
            FROM LAYANAN
            ORDER BY id DESC
            LIMIT 1
        ''')
        if len(res) == 0:
            database.query(f'''
                INSERT INTO LAYANAN VALUES 
                (1, '{nama}')
            ''')
        else:
            database.query(f'''
                INSERT INTO LAYANAN VALUES 
                ({res[0][0] + 1}, '{nama}')
            ''')
        return HttpResponseRedirect('/layanan')


def platform(request):

    database = Database(schema='office')

    if request.method == 'GET':
        res = database.query('''
            SELECT * 
            FROM PLATFORM
        ''')
        response = {
            'result': [
                {"id": pj[0],
                 "nama": pj[1]}
                for pj in res
            ]
        }
        return render(request, 'main/platform.html', response)

    else:
        nama = request.POST.get('nama')
        res = database.query('''
            SELECT id
            FROM PLATFORM
            ORDER BY id DESC
            LIMIT 1
        ''')
        if len(res) == 0:
            database.query(f'''
                INSERT INTO PLATFORM VALUES 
                (1, '{nama}')
            ''')
        else:
            database.query(f'''
                INSERT INTO PLATFORM VALUES 
                ({res[0][0] + 1}, '{nama}')
            ''')
        return HttpResponseRedirect('/platform')


def pengalaman(request):

    database = Database(schema='office')

    if request.method == 'GET':

        response = {}
        res = database.query('''
            SELECT nama
            FROM PENGGUNA_JASA
        ''')
        response['penggunaJasa'] = [pj[0] for pj in res]
        res = database.query('''
            SELECT nama
            FROM PEKERJAAN
        ''')
        response['pekerjaan'] = [p[0] for p in res]
        res = database.query('''
            SELECT nama
            FROM LAYANAN
        ''')
        response['layanan'] = [l[0] for l in res]
        res = database.query('''
            SELECT nama
            FROM PLATFORM
        ''')
        response['platform'] = [p[0] for p in res]
        response['year'] = range(2020, 2010, -1)

        res = database.query('''
            SELECT *
            FROM PENGALAMAN
        ''')

        response['pengalaman'] = [
            {'tahun': p[1], 'pj': p[2], 'pekerjaan': p[3], 'nilai': p[4], 'layanan': p[5],
             'platform': p[8], 'periode': p[6].strftime("%d %b %Y") + ' - ' + p[7].strftime("%d %b %Y")}
            for p in res
        ]

        return render(request, 'main/pengalaman.html', response)

    else:

        dct = dict(request.POST.lists())

        tahun = dct.get('tahun')[0]
        penggunaJasa = dct.get('penggunaJasa')[0]
        pekerjaan = dct.get('pekerjaan')[0]
        nilai = dct.get('nilai')[0]
        layanan = dct.get('layanan')[0]
        platforms = dct.get('platform')
        periode_start = dct.get('ps')[0]
        periode_end = dct.get('pe')[0]

        res = database.query('''
            SELECT id
            FROM PENGALAMAN
            ORDER BY id DESC
            LIMIT 1
        ''')

        platforms = ', '.join(platforms)
        if len(res) == 0:
            database.query(f'''
                INSERT INTO PENGALAMAN VALUES 
                (1, '{tahun}', '{penggunaJasa}', '{pekerjaan}', {nilai}, '{layanan}', '{periode_start}', '{periode_end}', '{platforms}')
            ''')
        else:
            database.query(f'''
                INSERT INTO PENGALAMAN VALUES 
                ({res[0][0] + 1}, '{tahun}', '{penggunaJasa}', '{pekerjaan}', {nilai}, '{layanan}', '{periode_start}', '{periode_end}', '{platforms}')
            ''')

        return HttpResponseRedirect('/pengalaman')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>
{% endblock meta %}

{% block content %}

<h1>
  Home
</h1>


<a href="{% url 'main:pengalaman' %}">Pengalaman</a>
<br>
<a href="{% url 'main:penggunaJasa' %}">Pengguna Jasa</a>
<br>
<a href="{% url 'main:pekerjaan' %}">Pekerjaan</a>
<br>
<a href="{% url 'main:layanan' %}">Layanan</a>
<br>
<a href="{% url 'main:platform' %}">Platform</a>


{% endblock content %}

main/templates/main/layanan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Layanan</title>
{% endblock meta %}

{% block content %}

<h2>Layanan</h2>

<form action="" method="POST">
    {% csrf_token %}
    <input name="nama" type="text">
    <button type="submit">
        ADD
    </button>
</form>
<br>
<table border="1px solid black">
    <tr>
        <td>No</td>
        <td>Nama</td>
    </tr>
    {% for res in result %}
    <tr>
        <td>{{res.id}}</td>
        <td>{{res.nama}}</td>
    </tr>
    {% endfor %}
</table>


{% endblock content %}

main/templates/main/pekerjaan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Pekerjaan</title>
{% endblock meta %}

{% block content %}

<h2>Pekerjaan</h2>

<form action="" method="POST">
    {% csrf_token %}
    <input name="nama" type="text">
    <button type="submit">
        ADD
    </button>
</form>
<br>
<table border="1px solid black">
    <tr>
        <td>No</td>
        <td>Nama</td>
    </tr>
    {% for res in result %}
    <tr>
        <td>{{res.id}}</td>
        <td>{{res.nama}}</td>
    </tr>
    {% endfor %}
</table>


{% endblock content %}

main/templates/main/pengalaman.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Platform</title>
{% endblock meta %}

{% block content %}

<h2>Pengalaman</h2>

<form action="" method="POST">
    {% csrf_token %}
    <select name="tahun" required>
        {% for i in year %}
        <option>{{i}}</option>
        {% endfor %}
    </select>
    <br>
    <select name="penggunaJasa" required>
        {% for pj in penggunaJasa %}
        <option>{{ pj }}</option>
        {% endfor %}
    </select>
    <br>
    <select name="pekerjaan" required>
        {% for p in pekerjaan %}
        <option>{{ p }}</option>
        {% endfor %}
    </select>
    <br>
    <input name="nilai" type="number" required>
    <br>
    <select name="layanan" required>
        {% for l in layanan %}
        <option>{{ l }}</option>
        {% endfor %}
    </select>
    <br>
    <div id="platforms">
        <select name="platform">
            {% for p in platform %}
            <option>{{ p }}</option>
            {% endfor %}
        </select>
    </div>
    <a href="#" id="tambah">➕</a>
    <br>
    <input name="ps" type="date" required>
    <br>
    <input name="pe" type="date" required>
    <br>
    <button type="submit">
        ADD
    </button>
</form>
<br>

<table border="1px solid black">
    <tr>
        <td>Tahun</td>
        <td>Pengguna Jasa</td>
        <td>Nama Pekerjaan</td>
        <td>Nilai</td>
        <td>Lingkup Layanan</td>
        <td>Platform</td>
        <td>Periode</td>
    </tr>
    {% for res in pengalaman %}
    <tr>
        <td>{{res.tahun}}</td>
        <td>{{res.pj}}</td>
        <td>{{res.pekerjaan}}</td>
        <td>{{res.nilai}}</td>
        <td>{{res.layanan}}</td>
        <td>{{res.platform}}</td>
        <td>{{res.periode}}</td>
    </tr>
    {% endfor %}
</table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'script.js' %}"></script>

{% endblock content %}

main/templates/main/penggunaJasa.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Pengguna Jasa</title>
{% endblock meta %}

{% block content %}

<h2>Pengguna Jasa</h2>

<form action="" method="POST">
    {% csrf_token %}
    <input name="nama" type="text">
    <button type="submit">
        ADD
    </button>
</form>
<br>
<table border="1px solid black">
    <tr>
        <td>No</td>
        <td>Nama</td>
    </tr>
    {% for res in result %}
    <tr>
        <td>{{res.id}}</td>
        <td>{{res.nama}}</td>
    </tr>
    {% endfor %}
</table>


{% endblock content %}

main/templates/main/platform.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Platform</title>
{% endblock meta %}

{% block content %}

<h2>Platform</h2>

<form action="" method="POST">
    {% csrf_token %}
    <input name="nama" type="text">
    <button type="submit">
        ADD
    </button>
</form>
<br>
<table border="1px solid black">
    <tr>
        <td>No</td>
        <td>Nama</td>
    </tr>
    {% for res in result %}
    <tr>
        <td>{{res.id}}</td>
        <td>{{res.nama}}</td>
    </tr>
    {% endfor %}
</table>


{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <a href="{% url 'main:home' %}">HOME</a>
  <br>
  {% block content %}
  {% endblock content %}

</body>

</html>